config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root 'questions#index'

  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question, :dependent => :destroy
  belongs_to :user

  validates :question, presence: true
  validates :description, presence: true, length: { minimum: 50 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  belongs_to :best_answer, class_name: 'Answer'

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers


  def self.from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

      find_or_create_by(provider: provider, uid: uid) do |user|
        user.provider = provider
        user.uid = uid
        # user.email = auth.info.email
        user.name = auth.info.name
        # user.avatar_url = auth.info.image
      end
  end
end






# where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
#   user.provider = auth.provider
#   user.uid      = auth.uid
#   user.name     = auth.info.name
#   user.save
# end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    @answer = Answer.order(created_at: :desc)
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      redirect_to question_path(@question), notice: 'Answer Created Successfully!'
    else
      render "questions/show"
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:description, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :desc)
    if @question.best_answer
      @answers = @answers - [@question.best_answer]
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question Created Successfully!'
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    notices = []

    if params[:best_answer_id]
      notices << 'Successfully updated best answer'
    end

    notices << 'Question Edited Successfully!'

    if @question.update(question_params)
      redirect_to @question, notice: notices
    else
      render :edit
    end
  end

  def destroy
    @question = Question.destroy(params[:id])
    redirect_to questions_path, notice: "Question #{@question.title} successfully deleted!"
  end

  private
  def question_params
    params.require(:question).permit(:title, :description, :best_answer_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_answer_form.html.erb
<%= form_for [@question, @answer] do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit class: 'button tiny'%>
  </div>

<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash flash-<%= type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_question_form.html.erb
<%= form_for(@question, html: { class: "new_question" }) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">My Site</a></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li class="active"><a href="#">Right Button Active</a></li>
          <li class="has-dropdown">
            <a href="#">Right Button Dropdown</a>
            <ul class="dropdown">
              <li><a href="#">First link in dropdown</a></li>
              <li class="active"><a href="#">Active link in dropdown</a></li>
            </ul>
          </li>
        </ul>

        <!-- Left Nav Section -->
        <ul class="left">
          <li><a href="#">Left Nav Button</a></li>
        </ul>
      </section>
    </nav>

    <%= render "layouts/flash" %>

    <div class="row">
      <%= yield %>
    </div>

  </body>
</html>

app/views/questions/edit.html.erb
question edit page

<%= render "layouts/question_form" %>

app/views/questions/index.html.erb
<h1>questions R us</h1>

<%= link_to 'New Question', new_question_path %>

<ul>
  <% @questions.each do |question| %>
    <li>
      <%= link_to "#{question.title}", question_path(question) %>
    </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
new question page

<%= form_for(@question, html: { class: "new_question" }) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<!-- <form method="post" action="<%= questions_path %>">
  <label for="Title">Title</label>
  <input type="text" name="question[title]" id="title" value="<%= @question.title %>" required>
  <label for="Description">Description</label>
  <input type="text" name="question[description]" id="description" value="<%= @question.description %>" required>
  <input type="submit" value="Add">
</form> -->

app/views/questions/show.html.erb
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, highlight: true) %>

question show page

Title: <%= @question.title %>
Description:
<%= markdown.render(@question.description).html_safe %>


<%= link_to 'Edit Question', edit_question_path(@question) %>
<%= button_to 'Delete Question', @question, { method: :delete, class: 'button tiny' } %>

New Answer:

<%= render "layouts/answer_form" %>

<% if @answers.nil? %>
No answers yet!
<% else %>
  Answers:
  <ul class="answer-list">
    <% if @question.best_answer %>
      <h3>Best Answer</h3>
      <li class="best-answer">
        <%= markdown.render(@question.best_answer.description).html_safe %>
      </li>
      <hr>
    <% else %>
      No Best Answer Chosen Yet!
    <% end %>

    <% @answers.each do |answer| %>
    <li class="other-answer">
      <%= button_to 'Best Answer', { controller: 'questions', action: 'update', question: { best_answer_id: answer.id } }, { method: 'patch', class: 'button tiny' }  %>
      <%= markdown.render(answer.description).html_safe %>
    </li>
    <% end %>
  </ul>
<% end %>